image: bluebox/giftwrap
#notify:
#  slack:
#    webhook_url: $$slack_url
#    on_started: true
#    on_success: true
#    on_failure: true
script:
  - pip install virtualenv
  - mkdir -p pkg && cd pkg
  - giftwrap build -m ../manifest.yml
  - ls -alh
  - cd ..
publish:
  swift:
    username: $$os_username
    password: $$os_password
    auth_url: $$os_auth_url
    container: packages
    source: pkg/
    target: giftwrap-demo/
    region: RegionOne
